name: Java CI with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17 and restore server cache
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and cache server with Maven
        run: |
          git clone https://github.com/G2D2-Game/server server
          cd server
          mvn -B package --file pom.xml


      - name: Build client with Maven
        run: mvn -B package --file client/pom.xml
