name: Java CI with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out client repository
        uses: actions/checkout@v3
        with:
          repository: G2D2-Game/client
          path: client
          ref: main

      - name: Check out server repository
        uses: actions/checkout@v3
        with:
          repository: G2D2-Game/server
          path: server
          ref: main

      - name: Set up JDK 17 and restore server cache
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build server with Maven
        run: mvn -B package --file server/pom.xml

      - name: Build client with Maven
        run: mvn -B package --file client/pom.xml
